# -*- coding: utf-8 -*-
"""Measure placement quality, so "this looks badly placed" becomes a number.

placement_gate.py answers pass/fail on a handful of hard rules. This answers "is
this a good layout", which is the question you actually want before spending
half an hour of routing on it. Nothing here fails a build; it prints metrics, and
the point is to compare two placements of the same board.

    "C:/Program Files/KiCad/10.0/bin/python.exe" placement_quality.py <board.kicad_pcb> [<board2> ...]

The metrics, and why each one is the thing an experienced layout engineer looks at:

  TOTAL CONNECTION LENGTH -- the sum over nets of a minimum spanning tree across
    that net's pads. It is the standard single-number summary of a placement:
    every millimetre here becomes a millimetre of trace, a via, or a detour, and
    the router cannot recover what the placement threw away.

  DECOUPLER REACH -- pad-to-pad from each bypass capacitor to the supply pin it
    bypasses. The loop is pin -> cap -> via -> plane, and its area is what decides
    the impedance at the frequencies that matter. Anything past ~2mm is a cap
    that is decorating the schematic rather than doing a job.

  SERIES ALIGNMENT -- for a two-pad part wired between two other parts, the angle
    between the part's own pad axis and the line joining those neighbours. A
    series element rotated across its own signal path forces the trace to leave
    sideways, turn, and come back: 0 degrees is a part that routes itself, 90 is
    one that fights.

  ESCAPE INTRUSION -- footprints inside the annulus a fine-pitch package needs for
    its own escape vias. A part parked there is not visible as an error until the
    router has already failed, which is how 11 MCU pins ended up stranded.

  NEIGHBOUR SPREAD -- mean distance from each part to the parts it shares a net
    with. Grouping is the cheapest routability there is, and this says whether
    blocks are actually clustered or merely nominally assigned to a region.
"""
import math
import os
import sys

import pcbnew

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import board_config

MM = pcbnew.ToMM

# Rails and grounds are excluded from the connection-length and grouping metrics:
# they are poured, so their "length" is not a routing cost and would swamp
# everything else.
# Which nets those are is the product's, so it comes from board_config.json.
# The fallback keeps a board that is not in any config measurable -- the metric
# then simply has nothing to exclude and says so by counting more nets.
DEFAULT_RAILS = ("GND",)
RAILS = DEFAULT_RAILS

# What counts as a supply pin worth bypassing. AGND is deliberately not here: it is
# a mid-rail REFERENCE generated by an op-amp, not a supply, and the parts sitting
# on it are biasing resistors rather than decouplers. Counting it made the metric
# blame C114 -- the 100uF AGND reservoir -- for "bypassing" a TLC14 pin 35mm away.
SUPPLY = ()


def _rails_for(board_path):
    """The poured nets on this board, from its config; DEFAULT_RAILS if unknown."""
    global RAILS, SUPPLY
    try:
        b = board_config.load().board_for_path(board_path)
        RAILS = tuple(b.get("supply_nets") or DEFAULT_RAILS)
    except Exception:
        RAILS = DEFAULT_RAILS
    # AGND is deliberately excluded from SUPPLY below: it is a mid-rail REFERENCE
    # generated by an op-amp, not a supply.
    SUPPLY = tuple(r for r in RAILS if r not in ("AGND", "GND"))

FINE_PITCH_MM = 0.55      # a package at or below this pitch needs an escape annulus
ESCAPE_MM = 8.0           # matches placement_gate.ESCAPE_ANNULUS


def pads_by_net(board):
    """-> {net: [(x, y, ref)]}, skipping poured nets."""
    nets = {}
    for fp in board.GetFootprints():
        ref = fp.GetReference()
        for pad in fp.Pads():
            n = pad.GetNetname()
            if not n or n in RAILS or n.startswith("unconnected-"):
                continue
            p = pad.GetPosition()
            nets.setdefault(n, []).append((MM(p.x), MM(p.y), ref))
    return nets


def mst_length(points):
    """Prim's, on a handful of points per net."""
    if len(points) < 2:
        return 0.0
    rest = list(range(1, len(points)))
    best = {i: math.dist(points[0][:2], points[i][:2]) for i in rest}
    total = 0.0
    while rest:
        i = min(rest, key=lambda k: best[k])
        total += best[i]
        rest.remove(i)
        for k in rest:
            d = math.dist(points[i][:2], points[k][:2])
            if d < best[k]:
                best[k] = d
    return total


def pin_types(board):
    """-> {(ref, pad): pintype}, for spotting real power pins."""
    out = {}
    for fp in board.GetFootprints():
        for pad in fp.Pads():
            out[(fp.GetReference(), pad.GetPadName())] = pad.GetPinType() or ""
    return out


def decoupler_reach(board):
    """-> [(cap ref, ic ref, pad, mm)] for every cap that bypasses a power pin."""
    fps = {fp.GetReference(): fp for fp in board.GetFootprints()}
    caps = {}
    for ref, fp in fps.items():
        if not ref.startswith("C"):
            continue
        nets = {p.GetNetname() for p in fp.Pads()}
        rail = [n for n in nets if n in SUPPLY]
        if len(nets) == 2 and rail and "GND" in nets:
            caps[ref] = rail[0]

    out = []
    for ref, fp in fps.items():
        if not ref.startswith("U"):
            continue
        for pad in fp.Pads():
            net = pad.GetNetname()
            if net not in SUPPLY:
                continue
            if "power" not in (pad.GetPinType() or ""):
                continue
            pp = pad.GetPosition()
            best = None
            for cref, crail in caps.items():
                if crail != net:
                    continue
                for cp in fps[cref].Pads():
                    if cp.GetNetname() != net:
                        continue
                    q = cp.GetPosition()
                    d = math.dist((MM(pp.x), MM(pp.y)), (MM(q.x), MM(q.y)))
                    if best is None or d < best[0]:
                        best = (d, cref)
            if best:
                out.append((best[1], ref, pad.GetPadName(), best[0]))
    return out


def series_alignment(board):
    """-> [(ref, degrees off the line joining its two neighbours)].

    Only two-pad parts whose two signal nets each reach at least one other part:
    those are the series elements whose rotation actually decides how they route.
    """
    fps = {fp.GetReference(): fp for fp in board.GetFootprints()}
    net_refs = {}
    for ref, fp in fps.items():
        for pad in fp.Pads():
            n = pad.GetNetname()
            if n and n not in RAILS and not n.startswith("unconnected-"):
                net_refs.setdefault(n, set()).add(ref)

    out = []
    for ref, fp in fps.items():
        pads = [p for p in fp.Pads()]
        if len(pads) != 2:
            continue
        n0, n1 = pads[0].GetNetname(), pads[1].GetNetname()
        if not n0 or not n1 or n0 == n1:
            continue
        if n0 in RAILS or n1 in RAILS:
            continue
        ends = []
        for net, own in ((n0, pads[0]), (n1, pads[1])):
            others = [r for r in net_refs.get(net, ()) if r != ref]
            if not others:
                break
            cx = sum(MM(fps[r].GetPosition().x) for r in others) / len(others)
            cy = sum(MM(fps[r].GetPosition().y) for r in others) / len(others)
            ends.append((cx, cy, own))
        if len(ends) != 2:
            continue
        want = math.atan2(ends[1][1] - ends[0][1], ends[1][0] - ends[0][0])
        a, bpad = ends[0][2].GetPosition(), ends[1][2].GetPosition()
        got = math.atan2(MM(bpad.y) - MM(a.y), MM(bpad.x) - MM(a.x))
        err = abs(math.degrees(want - got)) % 180.0
        out.append((ref, min(err, 180.0 - err)))
    return out


def escape_intrusions(board):
    """-> [(fine-pitch ref, intruder ref, mm)] inside the escape annulus."""
    fine = []
    for fp in board.GetFootprints():
        pads = [p for p in fp.Pads()]
        if len(pads) < 20:
            continue
        xs = sorted(MM(p.GetPosition().x) for p in pads)
        gaps = [b - a for a, b in zip(xs, xs[1:]) if b - a > 0.01]
        if gaps and min(gaps) <= FINE_PITCH_MM:
            fine.append(fp)

    out = []
    for f in fine:
        fc = f.GetPosition()
        for fp in board.GetFootprints():
            if fp is f or fp.GetReference().startswith(("H", "FID")):
                continue
            p = fp.GetPosition()
            d = math.dist((MM(fc.x), MM(fc.y)), (MM(p.x), MM(p.y)))
            if d < ESCAPE_MM:
                out.append((f.GetReference(), fp.GetReference(), d))
    return out


def neighbour_spread(board):
    """-> mean mm from each part to the parts it shares a signal net with."""
    fps = {fp.GetReference(): fp for fp in board.GetFootprints()}
    net_refs = {}
    for ref, fp in fps.items():
        for pad in fp.Pads():
            n = pad.GetNetname()
            if n and n not in RAILS and not n.startswith("unconnected-"):
                net_refs.setdefault(n, set()).add(ref)
    tot, cnt = 0.0, 0
    for ref, fp in fps.items():
        peers = set()
        for pad in fp.Pads():
            peers |= net_refs.get(pad.GetNetname(), set())
        peers.discard(ref)
        if not peers:
            continue
        p = fp.GetPosition()
        for q in peers:
            r = fps[q].GetPosition()
            tot += math.dist((MM(p.x), MM(p.y)), (MM(r.x), MM(r.y)))
            cnt += 1
    return tot / cnt if cnt else 0.0


def report(path):
    b = board_config.load_board(pcbnew, path)
    nets = pads_by_net(b)
    total = sum(mst_length(pts) for pts in nets.values())

    dec = decoupler_reach(b)
    far = [d for d in dec if d[3] > 2.0]

    align = series_alignment(b)
    bad_align = [a for a in align if a[1] > 30.0]

    intr = escape_intrusions(b)
    spread = neighbour_spread(b)

    print("=" * 74)
    print(os.path.basename(path))
    print("=" * 74)
    print("  total connection length   %8.1f mm   (%d signal nets)"
          % (total, len(nets)))
    print("  neighbour spread          %8.1f mm   (mean, lower is tighter grouping)"
          % spread)
    if dec:
        worst = max(dec, key=lambda d: d[3])
        print("  decoupler reach           %8.2f mm   mean, %.2f worst (%s -> %s.%s)"
              % (sum(d[3] for d in dec) / len(dec), worst[3], worst[0], worst[1], worst[2]))
        print("  decouplers beyond 2mm     %8d      of %d" % (len(far), len(dec)))
    if align:
        print("  series alignment          %8.1f deg  mean off-axis (0 = routes itself)"
              % (sum(a[1] for a in align) / len(align)))
        print("  series parts >30deg off   %8d      of %d" % (len(bad_align), len(align)))
    print("  escape-annulus intruders  %8d" % len(intr))
    if far:
        print("  --- decouplers beyond 2mm ---")
        for c, ic, pad, d in sorted(far, key=lambda t: -t[3])[:10]:
            print("      %-6s bypasses %s.%-3s at %.2f mm" % (c, ic, pad, d))
    if bad_align:
        print("  --- worst series alignment ---")
        for ref, err in sorted(bad_align, key=lambda t: -t[1])[:10]:
            print("      %-6s %5.1f deg off its own signal axis" % (ref, err))
    print("")


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    for p in sys.argv[1:]:
        _rails_for(p)
        report(p)
    return 0


if __name__ == "__main__":
    sys.exit(main())
