#pragma once
#include "font.hpp"

// Generated by tools/gen_fonts.py from tools/fonts/ — do not edit by hand.
namespace display {
extern const Font FONT_NAME;  // preset name, 12pt (~17px)
extern const Font FONT_NAME_MD;  // preset name, 10pt header fallback (~14px)
extern const Font FONT_NAME_SM;  // preset name, 8pt header fallback (~11px)
extern const Font FONT_TEXT;  // algorithm / param names + value magnitudes (9px)
extern const Font FONT_SMALL;  // page indicator / units / message (4x6)
}  // namespace display
